### ISSUE TITLE
Fix markdown list

### ISSUE THREAD

**Issue by mezotv** [Would-You-Bot/website#37]
Currently the markdown lists are broken where they display the actual list icon above the text content looking like sl ![image-116.png](https://github.com/Would-You-Bot/website/assets/68947960/c61cba05-4a41-45dd-9c27-6169007c0486)

![image-113.png](https://github.com/Would-You-Bot/website/assets/68947960/66e8345b-ddb8-4d5f-9015-b8a2beb15bfa)

**Comment by anniepauline** [comment]
@mezotv how do you want the list to be?

**Comment by mezotv** [comment]
> @mezotv how do you want the list to be?
> Under which component is the list broken?

Im not sure which one it is but it shluld display in the same line as the text see Screenshot 1.

**Comment by Mambinge** [comment]
Interested, anyone working on this? @mezotv

**Comment by Mambinge** [comment]
Any idea, where this file is at?

**Comment by mezotv** [comment]
> Any idea, where this file is at?

Probably either here https://github.com/Would-You-Bot/website/blob/main/pages/blog/%5Bslug%5D.tsx or here https://github.com/Would-You-Bot/website/blob/main/pages/blog/index.tsx

**Comment by gxrsti** [comment]
Out of curiosity, I checked the issue and encountered it only once, right at the beginning. I have been unable to replicate the behaviour since then, which seems weird.

Could you attempt to reproduce this, @mezotv?

**Comment by mezotv** [comment]
> Out of curiosity, I checked the issue and encountered it only once, right at the beginning. I have been unable to replicate the behaviour since then, which seems weird.
> 
> Could you attempt to reproduce this, @mezotv?

This happens when there is an empty line between one list item and another like here 
![image](https://github.com/Would-You-Bot/website/assets/68947960/71be4a33-a667-42e8-b2c9-12d5c305bd24)

**Comment by gxrsti** [comment]
Thanks for the information! I've done some investigation, and here's what I found:

Removing the `list-style-position: inline` from the ul element will render the list correctly.

If you look at the elements, the package wraps our seperated list items in one `<ul/>` and wraps the content of the list items in a `<p/>` tag. 

![image](https://github.com/Would-You-Bot/website/assets/88879471/2a642301-7c1f-400a-ad20-82b915dcd739)


What's interesting is that non-separated list items won't contain the `<p/>` tag.

![image](https://github.com/Would-You-Bot/website/assets/88879471/107117ad-1e5e-4589-97a3-c35099efd8ea)


I honestly don't see a reason for putting an empty line between two list elements in markdown, but a workaround that fixes this issue is to seperate the items with an empty tag like this:

![image](https://github.com/Would-You-Bot/website/assets/88879471/fdfeb41b-b484-45b7-80c8-342ec0fa23bd)

I hope this helps!

**Comment by Podskio** [comment]
@gxrsti Thank you for the help!
